#!/usr/bin/env bash
# Provision a per-symbol bar-history database: <symbol>_bar_history   (v3)
#
# Usage: ./provision_symbol_bar_history.sh ES 0.25 continuous_backadjusted
#        ./provision_symbol_bar_history.sh ZB 0.03125 continuous_backadjusted
#        ./provision_symbol_bar_history.sh 6E 0.00005
#
# v3: the bar schema is split into three ordered files
#       symbol_base_bar_history.sql   (bar_meta, ingest_batches, helpers, roles)
#       symbol_renko_bar_history.sql  (renko_bricks + view + QA)
#       symbol_m1_bar_history.sql     (candles_m1 + view + QA)
# applied base -> renko -> m1 (renko and m1 both depend on the base). For
# provenance, each is stamped to a per-symbol/per-representation artifact
# name before it is applied, e.g. es_base_bar_history.sql,
# es_renko_bar_history.sql, es_m1_bar_history.sql.

set -euo pipefail

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
    echo "Usage: $0 <SYMBOL> <TICK_SIZE> [SERIES_KIND]" >&2
    echo "  e.g. $0 ES 0.25 continuous_backadjusted" >&2
    echo "  SERIES_KIND: contract_month | continuous_unadjusted |" >&2
    echo "               continuous_backadjusted | continuous_ratio_adjusted" >&2
    echo "  (defaults to 'unspecified' — corpus QA will flag it)" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYMBOL_UPPER=$(echo "$1" | tr '[:lower:]' '[:upper:]')
DB_SUFFIX=$(echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g')
DB_NAME="${DB_SUFFIX}_bar_history"
TICK_SIZE="$2"
SERIES_KIND="${3:-unspecified}"
TRADE_DB="${TRADE_DB:-trade_history}"

# Per-symbol stamped artifacts (provenance of exactly what was applied)
STAMP_DIR="${STAMP_DIR:-${SCRIPT_DIR}}"
BASE_SRC="${SCRIPT_DIR}/symbol_base_bar_history.sql"
RENKO_SRC="${SCRIPT_DIR}/symbol_renko_bar_history.sql"
M1_SRC="${SCRIPT_DIR}/symbol_m1_bar_history.sql"
BASE_STAMP="${STAMP_DIR}/${DB_SUFFIX}_base_bar_history.sql"
RENKO_STAMP="${STAMP_DIR}/${DB_SUFFIX}_renko_bar_history.sql"
M1_STAMP="${STAMP_DIR}/${DB_SUFFIX}_m1_bar_history.sql"

# tick_size must be a positive decimal number
if ! echo "${TICK_SIZE}" | grep -Eq '^[0-9]*\.?[0-9]+$'; then
    echo "ERROR: tick_size '${TICK_SIZE}' is not a valid decimal" >&2
    exit 1
fi

# require all three source files
for f in "${BASE_SRC}" "${RENKO_SRC}" "${M1_SRC}"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: missing source file $f (run extract_sources.py first)" >&2
        exit 1
    fi
done

# refuse to clobber an existing database
if psql -lqt | cut -d'|' -f1 | grep -qw "${DB_NAME}"; then
    echo "ERROR: database ${DB_NAME} already exists — refusing to overwrite." >&2
    echo "       Drop it explicitly first if re-provisioning is intended." >&2
    exit 1
fi

echo "Provisioning ${DB_NAME} for ${SYMBOL_UPPER} (tick_size=${TICK_SIZE}, series=${SERIES_KIND})..."

# Stamp per-symbol artifacts with a provenance header, byte-identical DDL below.
stamp() {  # $1=src  $2=dest  $3=representation-label
    { echo "-- STAMPED ARTIFACT: ${SYMBOL_UPPER} ${3} — generated by provision_symbol_bar_history.sh";
      echo "-- source: $(basename "$1")";
      cat "$1"; } > "$2"
}
stamp "${BASE_SRC}"  "${BASE_STAMP}"  base
stamp "${RENKO_SRC}" "${RENKO_STAMP}" renko
stamp "${M1_SRC}"    "${M1_STAMP}"    m1

createdb "${DB_NAME}"

# Apply base -> renko -> m1 in order; base carries the psql -v variables.
if ! psql -d "${DB_NAME}" -v ON_ERROR_STOP=1 \
     -v symbol="${SYMBOL_UPPER}" -v tick_size="${TICK_SIZE}" \
     -v series_kind="${SERIES_KIND}" \
     -f "${BASE_STAMP}"; then
    echo "ERROR: base schema failed — removing empty ${DB_NAME}" >&2
    dropdb "${DB_NAME}"; exit 1
fi
for step in "${RENKO_STAMP}" "${M1_STAMP}"; do
    if ! psql -d "${DB_NAME}" -v ON_ERROR_STOP=1 -f "${step}"; then
        echo "ERROR: $(basename "${step}") failed — removing ${DB_NAME}" >&2
        dropdb "${DB_NAME}"; exit 1
    fi
done

# Auto-register into the FDW hub if it exists in ${TRADE_DB}
if [ "$(psql -d "${TRADE_DB}" -tAc \
        "SELECT 1 FROM pg_namespace WHERE nspname='bars'" 2>/dev/null)" = "1" ]; then
    psql -d "${TRADE_DB}" -v ON_ERROR_STOP=1 \
         -c "SELECT bars.register_symbol('${SYMBOL_UPPER}')" > /dev/null
    echo "Registered ${SYMBOL_UPPER} in ${TRADE_DB} bars hub."
fi

echo "Done: ${DB_NAME} (base + renko + m1; stamped ${DB_SUFFIX}_{base,renko,m1}_bar_history.sql)"

