#!/usr/bin/env python3
"""Derive the §2.4 binding table by RUNNING the suite and watching the gates.

ARC 027 / 0.2. Drives `scripts/tests` once under `binding_tracer`, collects
every verdict the real check code produced, and reports, per registered check,
whether a committed artifact drove it to a **failing** status.

## Why a failing status and not merely "a non-PASS"

`CANNOT_MEASURE` is the status a check returns when its subject is unavailable,
and a control that only ever produced CANNOT_MEASURE has demonstrated that the
check notices an absent subject — not that it notices a broken one. Under §10 of
the check contract that is explicitly *not* a proof of the safety property. So
the binding verdict keys on `FAIL_REPAIRABLE`/`FAIL_NEEDS_OPERATOR`, and
CANNOT_MEASURE and GUARDED are reported in their own columns rather than being
quietly counted as red.

## §7.12 — what would have to be true for this to publish a table while
## measuring nothing?

1. **The tracer never installs**, and every check reads UNBOUND. That is not a
   worse table, it is a WRONG one, and it looks exactly like a catastrophe.
   *Closed:* zero observations of any kind, or fewer than
   `MIN_CREDIBLE_OBSERVATIONS`, is a refusal (exit 2) rather than a table.
2. **The suite never ran.** A pytest that collected nothing exits 5 and would
   otherwise yield the same empty file. *Closed:* the pytest exit code is
   checked, and 5 (no tests collected) is a refusal.
3. **The check population could come from the observations themselves**, in
   which case a check nobody touched would silently not be a row — which is
   D3.25's defect exactly, an unclaimed binding attracting no audit. *Closed:*
   rows are enumerated from `checks/check_*.py` ON DISK, so a check with zero
   observations is a loud UNBOUND row rather than an absent one.
4. **A red observed in a COPY could be read as the shipped gate's.** *Closed by
   separation:* `real` and `copy` are distinct columns and the verdict keys on
   `real`. A check bound only through copies is reported as such.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import os
import subprocess  # nosec B404 - fixed argv, shell=False, this repo's own suite
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

#: Statuses that constitute a demonstrated can-fail. See the docstring.
FAILING = frozenset({"FAIL_REPAIRABLE", "FAIL_NEEDS_OPERATOR"})
#: Reported, never counted as a binding.
DEFERRING = frozenset({"CANNOT_MEASURE", "GUARDED"})

#: Below this the instrument is not credible: the suite drives twenty-one gates
#: many times over, and a handful of observations means the monitor lost most of
#: them. Anchored to a floor, not to today's count (a moving anchor reddens on
#: the next test added).
MIN_CREDIBLE_OBSERVATIONS = 50

_SITECUSTOMIZE = """\
# Generated by scripts/tests/binding_census.py. Temporary, per-run.
import sys
sys.path.insert(0, {tests!r})
try:
    import binding_tracer  # noqa: F401
except Exception:  # pragma: no cover - never break a child we are observing
    pass
"""


def _env(out: Path, sitedir: Path) -> dict[str, str]:
    """The child environment: tracer on every interpreter, output file named."""
    from binding_tracer import (  # pylint: disable=import-outside-toplevel
        CHECKS_VAR,
        OUT_VAR,
    )

    parts = [str(sitedir), str(REPO / "scripts"), str(REPO / "scripts" / "tests")]
    existing = os.environ.get("PYTHONPATH", "")
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(parts + ([existing] if existing else []))
    env[OUT_VAR] = str(out)
    env[CHECKS_VAR] = str(REPO / "checks")
    return env


def run_suite(out: Path, sitedir: Path, extra: list[str]) -> int:
    """Run the whole committed suite once, traced. Returns pytest's exit code."""
    sitedir.mkdir(parents=True, exist_ok=True)
    (sitedir / "sitecustomize.py").write_text(
        _SITECUSTOMIZE.format(tests=str(REPO / "scripts" / "tests")), encoding="utf-8"
    )
    return subprocess.run(  # nosec B603 - fixed argv, shell=False
        [
            sys.executable,
            "-m",
            "pytest",
            "-q",
            "-p",
            "binding_tracer",
            str(REPO / "scripts" / "tests"),
            *extra,
        ],
        cwd=str(REPO),
        env=_env(out, sitedir),
        check=False,
    ).returncode


def registered_checks() -> list[str]:
    """Every check ON DISK — the row set, so a silent gate is still a row."""
    return sorted(path.stem for path in (REPO / "checks").glob("check_*.py"))


def read_observations(out: Path) -> list[dict]:
    """Parse the JSONL the tracer appended. A torn final line is dropped."""
    if not out.is_file():
        return []
    rows = []
    for line in out.read_text(encoding="utf-8").splitlines():
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return rows


def shipped_digests(checks: list[str]) -> dict[str, str]:
    """sha256 of each shipped `checks/check_*.py`, as the census reads them now."""
    out = {}
    for name in checks:
        path = REPO / "checks" / f"{name}.py"
        out[name] = (
            hashlib.sha256(path.read_bytes()).hexdigest() if path.is_file() else ""
        )
    return out


def census(observations: list[dict], checks: list[str]) -> dict[str, dict]:
    """Per check: which statuses were seen, and by WHICH BYTES.

    The three buckets are the whole point of the refinement. `shipped` is the
    gate's own bytes, wherever on disk they were executed from — a control that
    copies the gate into `tmp_path` to plant against a fixture tree is still
    running the shipped gate, and calling that a lesser binding would have
    demoted three gates for a reason that is about directories rather than about
    code. `modified` is a gate whose SOURCE differs from what ships: that red
    was produced by a program this repository does not install, and it binds
    nothing. `unknown` is an unreadable digest, which is never silently merged
    into either.
    """
    digests = shipped_digests(checks)
    by_check: dict[str, dict] = {
        name: {
            "shipped": collections.Counter(),
            "modified": collections.Counter(),
            "unknown": collections.Counter(),
            "tests": set(),
            "modified_paths": set(),
        }
        for name in checks
    }
    for row in observations:
        name = row.get("check", "")
        entry = by_check.get(name)
        if entry is None:
            continue
        sha = str(row.get("sha", ""))
        if not sha:
            where = "unknown"
        elif sha == digests.get(name, ""):
            where = "shipped"
        else:
            where = "modified"
            entry["modified_paths"].add(str(row.get("module", "")))
        status = str(row.get("status", ""))
        entry[where][status] += 1
        if where == "shipped" and status in FAILING and row.get("test"):
            entry["tests"].add(str(row["test"]))
    return by_check


def verdict(entry: dict) -> str:
    """BOUND / BOUND-BY-MODIFIED-GATE / EXERCISED / UNBOUND, from counters alone."""
    if any(status in FAILING for status in entry["shipped"]):
        return "BOUND"
    if any(status in FAILING for status in entry["modified"]):
        return "BOUND-BY-MODIFIED-GATE"
    if any(entry[key] for key in ("shipped", "modified", "unknown")):
        return "EXERCISED-NEVER-RED"
    return "UNBOUND"


def _owning_files(tests: set[str]) -> list[str]:
    """The test FILES behind a set of nodeids — the committed artifact (§0e)."""
    return sorted({nodeid.split("::", 1)[0] for nodeid in tests if nodeid})


def render(table: dict[str, dict]) -> None:
    """Print the census. One line per check, then the roll-up."""
    print(f"\n{'check':<32} {'verdict':<24} shipped-gate statuses | modified-gate")
    print("-" * 110)
    for name, entry in table.items():
        shipped = (
            ",".join(f"{k}:{v}" for k, v in sorted(entry["shipped"].items())) or "-"
        )
        modified = (
            ",".join(f"{k}:{v}" for k, v in sorted(entry["modified"].items())) or "-"
        )
        print(f"{name:<32} {verdict(entry):<24} {shipped}  |  {modified}")
        for path in _owning_files(entry["tests"]):
            print(f"{'':<32} {'':<24} artifact: {path}")
    tally = collections.Counter(verdict(entry) for entry in table.values())
    print("-" * 100)
    print("  ".join(f"{k}={v}" for k, v in sorted(tally.items())))


def main(argv: list[str] | None = None) -> int:
    """Run the suite traced, then publish the census. Refuses a blind run."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--json", dest="json_out", default="")
    parser.add_argument("--observations", default="")
    parser.add_argument("pytest_args", nargs="*", default=[])
    args = parser.parse_args(argv)

    with tempfile.TemporaryDirectory(prefix="nix-binding-") as tmp:
        out = Path(args.observations or Path(tmp) / "observations.jsonl")
        code = run_suite(out, Path(tmp) / "site", list(args.pytest_args))
        observations = read_observations(out)

    if code == 5:
        print("REFUSED: pytest collected no tests", file=sys.stderr)
        return 2
    if len(observations) < MIN_CREDIBLE_OBSERVATIONS:
        print(
            f"REFUSED: {len(observations)} observation(s), below the credibility "
            f"floor of {MIN_CREDIBLE_OBSERVATIONS} — the monitor did not install "
            "or did not fire, and an empty census is indistinguishable from a "
            "system with no bindings at all",
            file=sys.stderr,
        )
        return 2

    table = census(observations, registered_checks())
    render(table)
    if args.json_out:
        Path(args.json_out).write_text(
            json.dumps(
                {
                    name: {
                        "verdict": verdict(entry),
                        "shipped": dict(entry["shipped"]),
                        "modified": dict(entry["modified"]),
                        "unknown": dict(entry["unknown"]),
                        "modified_paths": sorted(entry["modified_paths"]),
                        "artifacts": _owning_files(entry["tests"]),
                    }
                    for name, entry in table.items()
                },
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
    print(f"\npytest exit {code}; {len(observations)} observation(s)")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    sys.exit(main())
